#!/usr/bin/env bash
# proxy-on.sh — dnsmasq+ipset+redsocks (Netflix+Sora), "self-healing"
set -Eeuo pipefail

# Derive repo root from script location so this works from any clone path.
# Set path vars before sourcing config.env — the ${VAR:-default} in that file
# will not override values that are already set.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DNSMASQ_DIR="${DNSMASQ_DIR:-$REPO_DIR/dnsmasq}"
REDSOCKS_DIR="${REDSOCKS_DIR:-$REPO_DIR/redsocks}"
echo "[info] repo root: $REPO_DIR"
# shellcheck source=../config.env
source "$REPO_DIR/config.env"

mkdir -p "$BASELINE_DIR"

say(){ printf '%s\n' "$*"; }

# Returns the suffix of every DOMAINS_* variable that has matching IPSET_V4_* and IPSET_V6_* vars.
# E.g. DOMAINS_NFX + IPSET_V4_NFX + IPSET_V6_NFX → "NFX"; DOMAINS_SORA + IPSET_V4_SORA + IPSET_V6_SORA → "SORA"
all_suffixes(){
  compgen -v | grep '^DOMAINS_' | sed 's/^DOMAINS_//' | sort | while read -r s; do
    local v4="IPSET_V4_${s}" v6="IPSET_V6_${s}"
    [[ -n "${!v4:-}" && -n "${!v6:-}" ]] && echo "$s"
  done
}

wait_for(){ # wait_for "desc" cmd...
  local d="$1"; shift
  for i in {1..40}; do "$@" >/dev/null 2>&1 && return 0; sleep 0.25; done
  say "[warn] timeout: $d"; return 1
}

detect_dns_backend(){
  if command -v resolvectl &>/dev/null && systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    echo "resolvectl"
  elif command -v nmcli &>/dev/null && nmcli -g GENERAL.CONNECTION device show "$IFACE" &>/dev/null 2>&1; then
    echo "nmcli"
  else
    echo "resolv.conf"
  fi
}

ensure_alias(){
  # make loopback alias portable; we don’t need a LAN alias anymore
  : # using 127.100.53.53 (no ip addr add needed)
}

generate_ipsets_conf(){
  # Write dnsmasq ipset= rules from config.env into dnsmasq.d/ipsets.conf.
  # This runs before the container starts so dnsmasq picks them up at launch.
  local dir="$DNSMASQ_DIR/dnsmasq.d"
  local out="$dir/ipsets.conf"
  mkdir -p "$dir"
  : > "$out"
  for suffix in $(all_suffixes); do
    local doms="DOMAINS_${suffix}" v4="IPSET_V4_${suffix}" v6="IPSET_V6_${suffix}"
    for d in ${!doms}; do printf 'ipset=/%s/%s,%s\n' "$d" "${!v4}" "${!v6}"; done >> "$out"
  done
  say "[ok] generated $out ($(wc -l < "$out") ipset rules)"
}

generate_dnsmasq_conf(){
  local out="$DNSMASQ_DIR/dnsmasq.conf"
  {
    printf '# Generated by proxy-on.sh — do not edit; configure via config.env\n'
    printf 'no-resolv\n'
    printf 'server=9.9.9.9\n'
    printf 'server=8.8.8.8\n'
    if [[ -n "${LAN_DNS:-}" ]]; then
      printf 'server=/%s\n' "$LAN_DNS"
    fi
    printf 'bind-interfaces\n'
    printf 'listen-address=%s,%s\n' "$DNSIP_LOOP" "$DNSIP_BRIDGE"
    printf 'cache-size=1000\n'
    printf 'log-queries\n'
    printf 'log-facility=-\n'
    printf 'conf-dir=/etc/dnsmasq.d/,*.conf\n'
  } > "$out"
  say "[ok] generated $out"
}

dnsmasq_up(){
  generate_dnsmasq_conf
  # force-recreate so the container always loads the freshly generated ipsets.conf
  ( cd "$DNSMASQ_DIR" && docker compose up -d --force-recreate )
  wait_for "dnsmasq $DNSIP_LOOP:53"   bash -lc "ss -lnup | grep -q '$DNSIP_LOOP:53'"
  wait_for "dnsmasq $DNSIP_BRIDGE:53" bash -lc "ss -lnup | grep -q '$DNSIP_BRIDGE:53'"
}

set_iface_dns(){
  local backend
  backend=$(detect_dns_backend)
  echo "$backend" > "$BASELINE_DIR/dns.backend"

  case "$backend" in
    resolvectl)
      sudo resolvectl dns "$IFACE" "$DNSIP_LOOP" || true
      sudo resolvectl flush-caches || true
      wait_for "resolvectl shows $DNSIP_LOOP" bash -lc "resolvectl status $IFACE | grep -q 'DNS Servers:.*$DNSIP_LOOP'"
      ;;
    nmcli)
      local conn
      conn=$(nmcli -g GENERAL.CONNECTION device show "$IFACE" 2>/dev/null)
      echo "$conn" > "$BASELINE_DIR/dns.nmcli.conn"
      nmcli -g ipv4.dns con show "$conn" 2>/dev/null > "$BASELINE_DIR/dns.nmcli.old-dns" || true
      nmcli -g ipv4.ignore-auto-dns con show "$conn" 2>/dev/null > "$BASELINE_DIR/dns.nmcli.old-ignore" || true
      sudo nmcli con mod "$conn" ipv4.dns "$DNSIP_LOOP" ipv4.ignore-auto-dns yes
      sudo nmcli con up "$conn"
      wait_for "nmcli shows $DNSIP_LOOP" bash -lc "nmcli -g ipv4.dns con show '$conn' | grep -qF '$DNSIP_LOOP'"
      ;;
    resolv.conf)
      cp /etc/resolv.conf "$BASELINE_DIR/resolv.conf.bak" 2>/dev/null || true
      { printf 'nameserver %s\n' "$DNSIP_LOOP"; cat /etc/resolv.conf; } | sudo tee /etc/resolv.conf > /dev/null
      ;;
  esac
  say "[ok] DNS on $IFACE → $DNSIP_LOOP (via $backend)"
}

ensure_sets(){
  for suffix in $(all_suffixes); do
    local v4="IPSET_V4_${suffix}" v6="IPSET_V6_${suffix}"
    sudo ipset create "${!v4}" hash:ip -exist \
      || { say "[err] failed to create ipset ${!v4} — check: sudo modprobe ip_set"; exit 1; }
    if [[ "$USE_IPV6" == "1" ]]; then
      sudo ipset create "${!v6}" hash:ip family inet6 -exist \
        || { say "[err] failed to create ipset ${!v6}"; exit 1; }
    fi
  done
}

prime_sets(){
  # Actively "tickle" dnsmasq so it fills the ipsets before rules go in.
  local dns="$DNSIP_LOOP"
  local all_domains=() first_v4=""
  for suffix in $(all_suffixes); do
    local doms="DOMAINS_${suffix}" v4="IPSET_V4_${suffix}"
    [[ -z "$first_v4" ]] && first_v4="${!v4}"
    for d in ${!doms}; do all_domains+=("$d"); done
  done

  for _ in $(seq 1 $PRIME_TRIES); do
    for d in "${all_domains[@]+"${all_domains[@]}"}"; do
      dig +short @"$dns" A "$d" >/dev/null 2>&1 || true
      [[ "$USE_IPV6" == "1" ]] && dig +short @"$dns" AAAA "$d" >/dev/null 2>&1 || true
    done
    sleep 0.2
    [[ -n "$first_v4" ]] || break
    local cnt
    cnt=$(sudo ipset list "$first_v4" 2>/dev/null | awk '/Number of entries/{print $4}')
    [[ -n "${cnt:-}" && "$cnt" -gt 0 ]] && break
  done
}

generate_redsocks_conf(){
  cat > "$REDSOCKS_DIR/redsocks.conf" <<EOF
base {
  log_debug = off;
  log_info  = on;
  daemon    = off;
  redirector = iptables;
}
redsocks {
  local_ip   = $REDHOST;
  local_port = $REDPORT;

  ip   = $DANTE_IP;
  port = $DANTE_PORT;
  type = socks5;
}
EOF
  say "[ok] generated $REDSOCKS_DIR/redsocks.conf ($DANTE_IP:$DANTE_PORT)"
}

ensure_redsocks(){
  ( cd "$REDSOCKS_DIR" && docker compose up -d --force-recreate )
  wait_for "redsocks $REDHOST:$REDPORT" bash -lc "ss -ltn | grep -q '${REDHOST//./\\.}:$REDPORT\\b'"
}

install_rules(){
  for suffix in $(all_suffixes); do
    local v4="IPSET_V4_${suffix}" v6="IPSET_V6_${suffix}"
    sudo iptables -t nat -C OUTPUT -p tcp -m set --match-set "${!v4}" dst -j REDIRECT --to-ports "$REDPORT" 2>/dev/null \
      || sudo iptables -t nat -I OUTPUT 1 -p tcp -m set --match-set "${!v4}" dst -j REDIRECT --to-ports "$REDPORT"
    if [[ "$BLOCK_QUIC" == "true" ]]; then
      sudo iptables -C OUTPUT -p udp --dport 443 -m set --match-set "${!v4}" dst -j REJECT 2>/dev/null \
        || sudo iptables -I OUTPUT 1 -p udp --dport 443 -m set --match-set "${!v4}" dst -j REJECT
    fi
    if [[ "$USE_IPV6" == "1" ]]; then
      sudo ip6tables -C OUTPUT -p tcp -m set --match-set "${!v6}" dst -j REJECT 2>/dev/null \
        || sudo ip6tables -I OUTPUT 1 -p tcp -m set --match-set "${!v6}" dst -j REJECT
      sudo ip6tables -C OUTPUT -p udp --dport 443 -m set --match-set "${!v6}" dst -j REJECT 2>/dev/null \
        || sudo ip6tables -I OUTPUT 1 -p udp --dport 443 -m set --match-set "${!v6}" dst -j REJECT
    fi
  done
}

save_baseline_once(){
  if [[ "$RESTORE_ON_OFF" == "true" ]]; then
    [[ -f "$BASELINE_DIR/iptables.v4"  ]] || sudo iptables-save  > "$BASELINE_DIR/iptables.v4"
    [[ -f "$BASELINE_DIR/ip6tables.v6" ]] || sudo ip6tables-save > "$BASELINE_DIR/ip6tables.v6"
    [[ -f "$BASELINE_DIR/ipset.save"   ]] || sudo ipset save     > "$BASELINE_DIR/ipset.save" || true
  fi
}

# ----------------- bring-up sequence -----------------
save_baseline_once
# clean stale nft rules that may reference old set names (safe no-op)
_nft_pat=$(for _s in $(all_suffixes); do _v="IPSET_V4_${_s}"; echo "${!_v}"; done | paste -sd'|')
sudo nft -a list ruleset 2>/dev/null \
| awk -v pat="($_nft_pat)" '
  $1=="table"{fam=$2;tab=$3}
  $1=="chain"{chn=$2}
  $0 ~ pat { for(i=1;i<=NF;i++) if($i=="handle") h=$(i+1); if(h) print "nft delete rule",fam,tab,chn,"handle",h; h="" }
' | sudo sh 2>/dev/null || true

ensure_alias
ensure_sets
generate_ipsets_conf
dnsmasq_up
[[ "$SELF_DNS" == "true" ]] && set_iface_dns
prime_sets

# print ipset population counts for all sets
say "[ok] ipset population after priming:"
for _s in $(all_suffixes); do
  for _setvar in "IPSET_V4_${_s}" "IPSET_V6_${_s}"; do
    _cnt=$(sudo ipset list "${!_setvar}" 2>/dev/null | awk '/Number of entries/{print $4}')
    say "  ${!_setvar}: ${_cnt:-0} entries"
  done
done

# refuse to continue if the first ipset is still empty (misconfig)
_first_v4_set=""
for _s in $(all_suffixes); do _v="IPSET_V4_${_s}"; _first_v4_set="${!_v}"; break; done
_first_cnt=$(sudo ipset list "$_first_v4_set" 2>/dev/null | awk '/Number of entries/{print $4}')
if [[ -z "${_first_cnt:-}" || "$_first_cnt" -eq 0 ]]; then
  say "[err] $_first_v4_set is empty — check dnsmasq ipset= lines & host DNS ($DNSIP_LOOP)"
  exit 1
fi

generate_redsocks_conf
ensure_redsocks
install_rules

echo "[ok] redsocks @ $(ss -ltn | awk '/'"$REDHOST"':'"$REDPORT"'/{print $4}')"
echo "[ok] nat OUTPUT redirects:"
sudo iptables -t nat -vnL OUTPUT | awk '/REDIRECT/ && /'"$REDPORT"'/ && /match-set/ {print}'
echo "[ok] Dante SOCKS test:"
( curl --max-time 5 --socks5 "$DANTE_IP:$DANTE_PORT" https://api.ipify.org && echo ) || echo "(Dante unreachable; rules still installed)"
echo "[done] Proxy ENABLED (Netflix + Sora)"
